/*
 * MATLAB Compiler: 4.0 (R14)
 * Date: Thu Mar 06 15:47:21 2014
 * Arguments: "-B" "macro_default" "-m" "-W" "main" "-T" "link:exe"
 * "EigenFace.m" 
 */


#ifdef __cplusplus
extern "C" {
#endif
const unsigned char __MCC_EigenFace_public_data[] = {'3', '0', '8', '1', '9',
                                                     'D', '3', '0', '0', 'D',
                                                     '0', '6', '0', '9', '2',
                                                     'A', '8', '6', '4', '8',
                                                     '8', '6', 'F', '7', '0',
                                                     'D', '0', '1', '0', '1',
                                                     '0', '1', '0', '5', '0',
                                                     '0', '0', '3', '8', '1',
                                                     '8', 'B', '0', '0', '3',
                                                     '0', '8', '1', '8', '7',
                                                     '0', '2', '8', '1', '8',
                                                     '1', '0', '0', 'C', '4',
                                                     '9', 'C', 'A', 'C', '3',
                                                     '4', 'E', 'D', '1', '3',
                                                     'A', '5', '2', '0', '6',
                                                     '5', '8', 'F', '6', 'F',
                                                     '8', 'E', '0', '1', '3',
                                                     '8', 'C', '4', '3', '1',
                                                     '5', 'B', '4', '3', '1',
                                                     '5', '2', '7', '7', 'E',
                                                     'D', '3', 'F', '7', 'D',
                                                     'A', 'E', '5', '3', '0',
                                                     '9', '9', 'D', 'B', '0',
                                                     '8', 'E', 'E', '5', '8',
                                                     '9', 'F', '8', '0', '4',
                                                     'D', '4', 'B', '9', '8',
                                                     '1', '3', '2', '6', 'A',
                                                     '5', '2', 'C', 'C', 'E',
                                                     '4', '3', '8', '2', 'E',
                                                     '9', 'F', '2', 'B', '4',
                                                     'D', '0', '8', '5', 'E',
                                                     'B', '9', '5', '0', 'C',
                                                     '7', 'A', 'B', '1', '2',
                                                     'E', 'D', 'E', '2', 'D',
                                                     '4', '1', '2', '9', '7',
                                                     '8', '2', '0', 'E', '6',
                                                     '3', '7', '7', 'A', '5',
                                                     'F', 'E', 'B', '5', '6',
                                                     '8', '9', 'D', '4', 'E',
                                                     '6', '0', '3', '2', 'F',
                                                     '6', '0', 'C', '4', '3',
                                                     '0', '7', '4', 'A', '0',
                                                     '4', 'C', '2', '6', 'A',
                                                     'B', '7', '2', 'F', '5',
                                                     '4', 'B', '5', '1', 'B',
                                                     'B', '4', '6', '0', '5',
                                                     '7', '8', '7', '8', '5',
                                                     'B', '1', '9', '9', '0',
                                                     '1', '4', '3', '1', '4',
                                                     'A', '6', '5', 'F', '0',
                                                     '9', '0', 'B', '6', '1',
                                                     'F', 'C', '2', '0', '1',
                                                     '6', '9', '4', '5', '3',
                                                     'B', '5', '8', 'F', 'C',
                                                     '8', 'B', 'A', '4', '3',
                                                     'E', '6', '7', '7', '6',
                                                     'E', 'B', '7', 'E', 'C',
                                                     'D', '3', '1', '7', '8',
                                                     'B', '5', '6', 'A', 'B',
                                                     '0', 'F', 'A', '0', '6',
                                                     'D', 'D', '6', '4', '9',
                                                     '6', '7', 'C', 'B', '1',
                                                     '4', '9', 'E', '5', '0',
                                                     '2', '0', '1', '1', '1'
                                                     , '\0'};

const char *__MCC_EigenFace_name_data = "EigenFace";

const char *__MCC_EigenFace_root_data = "";

const unsigned char __MCC_EigenFace_session_data[] = {'2', '5', 'C', '4', '8',
                                                      '2', '5', '4', '5', 'F',
                                                      '6', '3', '0', '7', '5',
                                                      '3', '0', 'B', '6', '0',
                                                      '3', '8', 'A', '4', 'E',
                                                      '1', '3', '9', '9', '3',
                                                      '4', '4', 'E', '3', '2',
                                                      '9', 'F', '7', '8', '3',
                                                      'B', 'F', '1', 'C', 'C',
                                                      'B', '8', '2', '7', '1',
                                                      '0', '3', '9', '7', '8',
                                                      '2', '9', '9', 'A', '0',
                                                      'B', '0', 'B', '8', 'A',
                                                      '4', '2', '2', '3', 'D',
                                                      'B', '3', '2', '9', 'B',
                                                      'A', '6', '3', '5', '3',
                                                      '1', '1', 'E', '8', 'C',
                                                      'A', 'F', '1', '9', '1',
                                                      'D', '4', '3', '4', 'E',
                                                      'D', 'E', '2', 'A', 'A',
                                                      'D', 'F', '4', 'C', 'B',
                                                      '2', '5', 'F', '7', '8',
                                                      'F', '7', 'A', 'B', '6',
                                                      '6', 'D', '0', 'A', 'F',
                                                      'C', 'A', '7', 'C', 'C',
                                                      '6', 'C', '7', '3', '5',
                                                      'C', 'C', '2', '7', '4',
                                                      '6', '0', '6', '5', 'A',
                                                      '2', '3', '3', 'A', '6',
                                                      'E', '0', 'B', '6', '8',
                                                      '2', '3', '7', '4', '1',
                                                      '6', 'F', '6', 'B', 'B',
                                                      'A', 'D', '1', '7', '0',
                                                      '7', 'A', 'D', '1', '6',
                                                      '7', '0', 'A', '9', 'F',
                                                      '7', '3', 'E', '0', '2',
                                                      'B', 'A', '8', '9', '2',
                                                      'B', 'F', 'D', '8', '1',
                                                      'F', '8', '4', '2', '9',
                                                      '8', '8', '1', '3', '6',
                                                      '3', '6', '4', '8', '4',
                                                      '5', '7', '9', '1', '2',
                                                      '9', '7', '3', 'C', 'B',
                                                      '2', '6', '7', '1', '3',
                                                      'C', '1', '8', '7', 'F',
                                                      '5', '8', '2', '4', 'D',
                                                      '8', 'D', '2', 'A', 'B',
                                                      'E', '7', '2', '8', 'E',
                                                      '0', 'C', '9', '1', '8',
                                                      'D', 'D', '5', '0', '6',
                                                      '3', '8', '0', '5', '2',
                                                      '1', '\0'};

const char *__MCC_EigenFace_matlabpath_data[] = {"EigenFace/",
                                                 "toolbox/compiler/deploy/",
                                                 "$TOOLBOXMATLABDIR/general/",
                                                 "$TOOLBOXMATLABDIR/ops/",
                                                 "$TOOLBOXMATLABDIR/lang/",
                                                 "$TOOLBOXMATLABDIR/elmat/",
                                                 "$TOOLBOXMATLABDIR/elfun/",
                                                 "$TOOLBOXMATLABDIR/specfun/",
                                                 "$TOOLBOXMATLABDIR/matfun/",
                                                 "$TOOLBOXMATLABDIR/datafun/",
                                                 "$TOOLBOXMATLABDIR/polyfun/",
                                                 "$TOOLBOXMATLABDIR/funfun/",
                                                 "$TOOLBOXMATLABDIR/sparfun/",
                                                 "$TOOLBOXMATLABDIR/scribe/",
                                                 "$TOOLBOXMATLABDIR/graph2d/",
                                                 "$TOOLBOXMATLABDIR/graph3d/",
                                                 "$TOOLBOXMATLABDIR/specgraph/",
                                                 "$TOOLBOXMATLABDIR/graphics/",
                                                 "$TOOLBOXMATLABDIR/uitools/",
                                                 "$TOOLBOXMATLABDIR/strfun/",
                                                 "$TOOLBOXMATLABDIR/imagesci/",
                                                 "$TOOLBOXMATLABDIR/iofun/",
                                                 "$TOOLBOXMATLABDIR/audiovideo/",
                                                 "$TOOLBOXMATLABDIR/timefun/",
                                                 "$TOOLBOXMATLABDIR/datatypes/",
                                                 "$TOOLBOXMATLABDIR/verctrl/",
                                                 "$TOOLBOXMATLABDIR/codetools/",
                                                 "$TOOLBOXMATLABDIR/helptools/",
                                                 "$TOOLBOXMATLABDIR/winfun/",
                                                 "$TOOLBOXMATLABDIR/demos/",
                                                 "toolbox/local/",
                                                 "toolbox/compiler/",
                                                 "toolbox/control/control/",
                                                 "toolbox/database/database/",
                                                 "toolbox/images/images/",
                                                 "toolbox/stats/"};
const int __MCC_EigenFace_matlabpath_data_count = 36;

const char *__MCC_EigenFace_mcr_application_options[] = { "" };
const int __MCC_EigenFace_mcr_application_option_count = 0;
const char *__MCC_EigenFace_mcr_runtime_options[] = { "" };
const int __MCC_EigenFace_mcr_runtime_option_count = 0;
#ifdef __cplusplus
}
#endif


